// Generated by DSL v0.3 (fixed)
$fn=72;

module t01_cube() {
  minkowski(){ translate([0,0,0]) cube([20.0,20.0,10.0], center=true); cylinder(r=2.0, h=0.01, center=true); }
  translate([0,0,0]) rotate([0,0,0]) t01_cube();
}

module t02_cyl() {
  minkowski(){ translate([0,0,0]) cylinder(r=8.0, h=30.0, center=true); cylinder(r=1.5, h=0.01, center=true); }
  translate([0,0,0]) rotate([0,0,0]) t02_cyl();
}

module t03_rodx() {
  translate([0.0,0.0,0.0]) rotate([0,90,0]) cylinder(r=3.0, h=60.0, center=true);;
  translate([0,0,0]) rotate([0,0,0]) t03_rodx();
}

module t04_torus() {
  translate([0.0,0.0,0.0]) rotate_extrude() translate([25.0,0,0]) circle(r=5.0);
  translate([0,0,0]) rotate([0,0,0]) t04_torus();
}

module t05_extrude() {
  linear_extrude(height=15:) { translate([0,0]) circle(r=10.0); }
  translate([0,0,0]) rotate([0,0,0]) t05_extrude();
}

module t06_cube() {
  translate([0,0,0]) cube([20.0,20.0,10.0], center=true);
}

module t06_cyl() {
  translate([0,0,0]) cylinder(r=9.0, h=10.0, center=true);
  translate([0,0,0]) rotate([0,0,0]) t06_union();
}

module t06_union() {
  union() { t06_cube(); t06_cyl(); }
}

module t07_cube() {
  translate([0,0,0]) cube([30.0,30.0,15.0], center=true);
}

module t07_cyl() {
  translate([0,0,0]) cylinder(r=10.0, h=20.0, center=true);
  translate([0,0,0]) rotate([0,0,0]) t07_cut();
}

module t07_cut() {
  difference() { t07_cube(); t07_cyl(); }
}

module t08_cube() {
  translate([0,0,0]) cube([30.0,30.0,30.0], center=true);
}

module t08_sph() {
  translate([0,0,0]) sphere(r=18.0);
  translate([0,0,0]) rotate([0,0,0]) t08_inter();
}

module t08_inter() {
  intersection() { t08_cube(); t08_sph(); }
}

module t09_a() {
  translate([0.0,0.0,0.0]) cube([20.0,10.0,10.0], center=true);
}

module t09_b() {
  translate([0.0,0.0,10.0]) cylinder(r=5.0, h=20.0, center=true);
}

module t09_grp() {
  translate([0,0,0]) rotate([0,0,0]) t09_a();
  translate([0,0,0]) rotate([0,0,0]) t09_b();
  translate([0,0,0]) rotate([0,0,0]) t09_grp();
}

module t10_block() {
  translate([0,0,0]) cube([10.0,10.0,10.0], center=true);
  translate([0.0,0.0,0.0]) rotate([0,0,0]) t10_block();
  translate([0.0,0.0,15.0]) rotate([0.0,0.0,45.0]) t10_block();
  translate([0.0,0.0,30.0]) rotate([0.0,0.0,90.0]) t10_block();
}

module t11_rody() {
  translate([0,0,0]) rotate([90,0,0]) cylinder(r=2.0, h=40.0, center=true);;
}

module t11_torus() {
  translate([0,0,0]) rotate_extrude() translate([15.0,0,0]) circle(r=3.0);
  translate([0,0,0]) rotate([0,0,0]) t11_join();
}

module t11_join() {
  union() { t11_rody(); t11_torus(); }
}

module t12_base() {
  minkowski(){ translate([0,0,0]) cube([40.0,40.0,6.0], center=true); cylinder(r=2.0, h=0.01, center=true); }
}

module t12_pillar() {
  translate([0.0,0.0,3.0]) cylinder(r=6.0, h=30.0, center=true);
  translate([0,0,0]) rotate([0,0,0]) t12_plate();
}

module t12_plate() {
  union() { t12_base(); t12_pillar(); }
}

module assembly(){
}
assembly();